version: '3'

services:
  traefik:
    image: traefik
    command: --api --docker # Enables the web UI and tells Træfik to listen to docker
    ports:
      - "8080:80"     # The HTTP port
      - "8081:8080" # The Web UI (enabled by --api)
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  consul:
    image: consul
    restart: unless-stopped
      ports:
        - 8500:8500

  den-travak:
    image: den-travak-app:0.0.1-SNAPSHOT
    restart: unless-stopped
    ports:
      - 8123:8080

  recommendation:
    image: recommendation-app:0.0.1-SNAPSHOT
    restart: unless-stopped
    ports:
      - 8124:8080