version: '3'

services:
  mysql:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=root123
      - MYSQL_DATABASE=den-travak-app
      - MYSQL_USER=dbuser
      - MYSQL_PASSWORD=dbp4ss
    volumes:
      - ./data/mysql3:/var/lib/mysql
  den-travak:
    image: den-travak-app:0.0.1-SNAPSHOT
    depends_on:
      - mysql
    restart: unless-stopped
    ports:
      - 8234:8080
    environment:
      - spring.profiles.active=container
      - DATABASE_HOST=mysql
      - DATABASE_USER=dbuser
      - DATABASE_PASSWORD=dbp4ss
      - DATABASE_NAME=den-travak-app
      - DATABASE_PORT=3306